apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: team03akv
spec:
  provider: azure
  parameters:
    keyvaultName: "team03akv"       # The name of the Azure Key Vault
    useVMManagedIdentity: "true"         
    userAssignedIdentityID: "f24cf5ab-5663-49f7-8917-3f67d59e75ee" # The clientId of the addon-created managed identity
    cloudName: ""                         # [OPTIONAL for Azure] if not provided, Azure environment will default to AzurePublicCloud 
    objects:  |
      array:
        - |
          objectName: SQL-SERVER       # In this example, 'ExampleSecret'
          objectAlias: SQL_SERVER          
          objectType: secret              # Object types: secret, key or cert
          objectVersion: ""               # [OPTIONAL] object versions, default to latest if empty
        - |
          objectName: SQL-USER       # In this example, 'ExampleSecret'   
          objectAlias: SQL_USER
          objectType: secret              # Object types: secret, key or cert
          objectVersion: ""               # [OPTIONAL] object versions, default to latest if empty
        - |
          objectName: SQL-PASSWORD       # In this example, 'ExampleSecret'   
          objectAlias: SQL_PASSWORD
          objectType: secret              # Object types: secret, key or cert
          objectVersion: ""               # [OPTIONAL] object versions, default to latest if empty        
    tenantId: "b874ec7f-aa44-41ae-b9f1-8fb74d08523f"               # the tenant ID containing the Azure Key Vault instance