---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: insurance-deployment
  namespace: insurance
  labels:
    deploy: insurance
spec:
  replicas: 2
  selector:
    matchLabels:
      app: insurance
  template:
    metadata:
      labels:
        app: insurance
    spec:
      containers:
      - image: "registryzxc7268.azurecr.io/insurance:1.0"
        imagePullPolicy: Always
        name: insurance
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: insurance-service
  namespace: insurance
spec:
  type: ClusterIP
  selector:
    app: insurance
  ports:
  - protocol: TCP
    name: insurance-http
    port: 80
    targetPort: 8081
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: insurance-ingress
  namespace: insurance
spec:
  rules:
  - http:
      paths: 
      - path: /insurance
        pathType: Prefix
        backend:
          service:
            name: insurance-service
            port:
              number: 80